### PR TITLE
Model v2

### PR DESCRIPTION
**Pull request by flinder**

### CODE REVIEW

**Comment by flinder** [comment]
Saw that too @vishakhpk . I think it would make sense to just merge model v_2 into the old `model.py` so we don't have multiple models floating around.

**Comment by yinleon** [comment]
Ok, I will replace the first model. My todo is

- [ ] Fix the sample function
- [ ] Test with data loader
- [ ] Update lockeddrop

**Comment by yinleon** [comment]
Training looks fine during the first 2 epochs; the numbers match the example notebook and the sentences are not ridiculous. However during the third epoch the losses increase dramatically and sentence generation just repeats words. This occurs both with cross entropy and NLLL!

**Comment by flinder** [comment]
@yinleon could you figure the problem with the third epoch out? I could look into it if it's still an issue

**Comment by flinder** [comment]
@yinleon @vishakhpk I think I fixed up everything and the new model seems to run fine (I don't see any deterioration after the first 2 epochs). 
Important things I did:
- I overwrote the old model with the new one. We can always go back in VC if we need anything from there
- I caught a small bug in the new model that caused a crash if running with only one lstm
- I updated the Example notebook to run with the new model

**Comment by flinder** [comment]
accidentally closed this

**Pull request merged**
